SELECT
    STAFF.EMP_CODE,
    STAFF.EMP_NAME,
    STAFF.DEPT_CODE,
    STAFF.EDUC_CODE,
    DEPT.DEPT_DESC,
    EDUCATE.EDUC_DESC,
    [SECTION].SECT_CODE,
    [SECTION].SECT_DESC,

    /* Existing totals */
    SUM(DAILY.OT15)      AS Sum_OT15,
    SUM(DAILY.OT20)      AS Sum_OT20,
    SUM(DAILY.LATE)      AS Sum_LATE,
    SUM(DAILY.[UNDER])   AS Sum_UNDER,
    SUM(DAILY.SHIFT_ALL) AS Sum_SHIFT_ALL,
    SUM(DAILY.MEAL_ALL)  AS Sum_MEAL_ALL,
    SUM(DAILY.TRAN_ALL)  AS Sum_TRAN_ALL,
    SUM(DAILY.OTH1_ALL)      AS Sum_OTH1_ALL,

    /* Working-day variations */
    SUM(CASE WHEN DAILY.REASON <> 'OFF' AND W.WorkTime >= 800 AND W.WorkTime < 1200 THEN 1 ELSE 0 END) AS Normal_8H,
    SUM(CASE WHEN DAILY.REASON <> 'OFF' AND W.WorkTime >= 1200 THEN 1 ELSE 0 END) AS Normal_12H,
    SUM(CASE WHEN DAILY.REASON = 'OFF' AND W.WorkTime >= 800 AND W.WorkTime < 1200 THEN 1 ELSE 0 END) AS Off_8H,
    SUM(CASE WHEN DAILY.REASON = 'OFF' AND W.WorkTime >= 1200 THEN 1 ELSE 0 END) AS Off_12H

FROM STAFF
INNER JOIN DEPT        ON DEPT.DEPT_CODE   = STAFF.DEPT_CODE
INNER JOIN EDUCATE     ON EDUCATE.EDUC_CODE = STAFF.EDUC_CODE
INNER JOIN [SECTION]   ON [SECTION].SECT_CODE = STAFF.SECT_CODE
INNER JOIN DAILY       ON DAILY.EMP_CODE   = STAFF.EMP_CODE
CROSS APPLY (SELECT (DAILY.TIMEOUT - DAILY.TIMEIN) AS WorkTime) W
WHERE STAFF.COM_CODE = N'0004'
  AND STAFF.EDUC_CODE IN (@EDUC_CODE)
  AND STAFF.DEPT_CODE IN (@DEPT_CODE)
  AND DAILY.[DATE] BETWEEN @DATE AND @DATE2
GROUP BY
    STAFF.EMP_CODE,
    STAFF.EMP_NAME,
    STAFF.DEPT_CODE,
    STAFF.EDUC_CODE,
    DEPT.DEPT_DESC,
    EDUCATE.EDUC_DESC,
    [SECTION].SECT_CODE,
    [SECTION].SECT_DESC;